#165413067 View and edit profile
andela/riders-ah-frontend pull request #16
Opened 2019-07-10 16:46 UTC by AJAkimana

Description
=======

This PR is for adding functionalities of  view and editing user profile

Type of change
=======
N/A

How has it been tested
=======
It can be tested by log in and access below  routes:

- View user profile: ``/profile``
- For updating user profile: ``/profile/edit`` .

Checklist:
=======
- Create redux actions
- Add actions reducers for getting and updating user info
- Create components for view and update profile
- Write tests

Pivotal tracker story ID
=======
[#165413067](https://www.pivotaltracker.com/n/projects/2326984/stories/165413067)

Screenshots
=======
<img width="1117" alt="Screen Shot 2019-07-10 at 18 45 02" src="https://user-images.githubusercontent.com/30657705/60987936-ed8b2900-a342-11e9-97cc-c54519056d02.png">
<img width="1154" alt="Screen Shot 2019-07-10 at 18 45 22" src="https://user-images.githubusercontent.com/30657705/60987949-f2e87380-a342-11e9-9546-fb94737a19b9.png">

[#165413067]

2019-07-15 10:13 UTC, Kabalisa reviewed
Good work @AJAkimana. I have a few suggestions you can put into this feature.
- add a way to return to view profile apart from clicking on save. in case, a user clicked edit profile by accident.
-find also a way to store and retrieve a user image as part of their profile
- after you can rebase

2019-07-15 10:15 UTC, ericnyirimana requested changes
Good work @AJAkimana. I'm suggesting that you can move the profile component from views to src/component. I'm also suggesting that when updating the user profile the BIO fields should be a text area. Thank you.

2019-07-16 09:34 UTC, ericnyirimana reviewed
Rebase your PR

2019-07-16 09:39 UTC, AJAkimana commented
> Rebase your PR

I did, and I'm about to push the changes

2019-07-16 19:04 UTC, jabichris commented on src/index.html
> +</html>
Add a new line here

2019-07-17 08:22 UTC, Kabalisa approved these changes

2019-07-17 08:38 UTC, ericnyirimana approved these changes

2019-07-17 12:51 UTC, macphilips commented on src/components/common/profileSideMenu.jsx
> +class ProfileSideMenu extends Component {
This can be converted to a functional component. eg
```js
export const ProfileSideMenu = ({ props1, props2 }) => (<div></div>)
```

2019-07-17 12:54 UTC, macphilips commented on src/components/profile/viewProfile.jsx
> +      user.nFollowers = totFollowers;
```suggestion
      user.numFollowers = totFollowers;
```

2019-07-22 09:51 UTC, merged