#165413072 Adds like and dislike functionality
andela/riders-ah-frontend pull request #17
Opened 2019-07-15 08:00 UTC by Niyitangasam

Description
=======

This PR is for adding functionalities of liking and disliking an article.

Type of change
=======
N/A

How has it been tested
=======
It can be tested by log in and access below  routes:

- You can access specific article on ``/articles/slug``.

Checklist:
=======
- Add components for liking and disliking an article.
- Add its actions and reducers
- Add necessary HTML and scss to the page
Pivotal tracker story ID
=======
[#165413072](https://www.pivotaltracker.com/n/projects/2326984/stories/165413072)

Screenshots
=======
![image](https://user-images.githubusercontent.com/12936280/61202284-61cd2000-a6e7-11e9-9b94-903efad13456.png)

2019-07-16 18:54 UTC, jabichris commented on src/components/common/navBar.jsx
> + export default NavBar;
Can you add a new line here?

2019-07-17 08:41 UTC, Kabalisa requested changes
@Niyitangasam Good work.  the feature is working fine. however, the design on the like and dislike icon is different from the one implemented in our templates. you can pick up the sass we used to change it.

2019-07-23 07:06 UTC, Kabalisa approved these changes
good work @Niyitangasam .

2019-07-23 07:35 UTC, jabichris commented on src/assets/scss/_oneStory.scss
> +
Add a new line here

2019-07-23 07:45 UTC, jabichris approved these changes
Nice work

2019-07-23 11:27 UTC, merged