Ft view articles 167064436
andela/riders-ah-frontend pull request #20
Opened 2019-07-15 08:59 UTC by jabichris

#### Description
This PR is for adding functionalities such as:
- View all articles functionality
-  View one article functionality
- Edit one article if you are the author
- Delete one article if you are the author

#### Type of change
N/A

#### How has it been tested
By going to `http://localhost:3002/articles` for all articles and `http://localhost:3002/articles/:slug` for one article.

 #### Pivotal tracker story ID
#167064436

2019-07-17 07:01 UTC, Niyitangasam reviewed
@jabichris , I am not able to test this feature on Heroku deployment.

2019-07-17 08:49 UTC, Kabalisa requested changes
@jabichris. on Heroku, an article is being rendered with HTML tags that it is stored as in the database. can you change that.

2019-07-17 09:41 UTC, jabichris commented
@Kabalisa, I worked on the changes you requested. You can Re-review

2019-07-17 11:38 UTC, Niyitangasam approved these changes

2019-07-17 12:17 UTC, Kabalisa approved these changes

2019-07-18 09:24 UTC, macphilips commented on src/components/articles/articleCard.jsx
> +  return (
please format the file properly

2019-07-18 09:24 UTC, macphilips commented on src/actions/delete.js
> +export const deleteOneStory = (slug) =>  dispatch => {
Please combine these files into one: `src/actions/delete.js`, `src/actions/oneStory.js`, `src/actions/viewArticles.js`

2019-07-18 09:24 UTC, macphilips commented on src/components/common/loader.jsx
> +class Loader extends Component{
Please apply proper formatting to this file
Also, make this a functional component

2019-07-18 09:57 UTC, merged