#165413085 like an article comment
andela/riders-ah-frontend pull request #34
Opened 2019-07-29 08:36 UTC by ericnyirimana

Description
=======

This PR is for liking a specific comment of an article

Type of change
=======
N/A

How has it been tested
=======
- You can access it by viweing one story article page and like a comment
Checklist:
=======
- Add liking component on viewing one article
Pivotal tracker story ID
=======
[#165413085](https://www.pivotaltracker.com/n/projects/2326984/stories/165413085)

Screenshots
=======
N/A

2019-07-31 08:54 UTC, Niyitangasam approved these changes

2019-07-31 08:55 UTC, jabichris approved these changes

2019-07-31 09:16 UTC, jabichris requested changes
Unable to test

2019-07-31 09:17 UTC, Niyitangasam requested changes
Can you check what's wrong with its deployment?

2019-07-31 09:49 UTC, jabichris approved these changes

2019-08-01 11:39 UTC, Niyitangasam approved these changes

2019-08-01 11:40 UTC, Niyitangasam approved these changes

2019-08-01 12:56 UTC, macphilips commented on src/tests/actions/likeComment.test.js
> +  expect(store.getActions().length).toBe(1);
Format this file properly

2019-08-01 13:08 UTC, merged